### PR TITLE
Fix date filter for format with colon

### LINKED ISSUE #37: Date filter returns null when colon used in "format" argument
`Published: {{ entry.published | date: '%d/%m/%Y %l %M %p'}}`

_Published: 09/05/1980 10 05 AM_

`{{ entry.published | date: '%d/%m/%Y %l:%M %p'}}`

_Published:_

I'm trying to find where in the code the colon is breaking this - any suggestions appreciated.

### PR DESCRIPTION
**Pull request by sanmai**
Should fix #37

May break something else, though all tests are passing fine.

### CODE REVIEW

**Comment by schmoove** [comment]
Can someone please merge this PR!

**Comment by kalimatas** [comment]
Thanks!

Will release new version after #33 is fixed.

Sorry guys for making you wait, but I really don't have much time to maintain this project.

**Comment by sanmai** [comment]
Do you think you could accept a co-maintainer?

**Comment by kalimatas** [comment]
@sanmai That would be nice.

**Comment by sanmai** [comment]
Great, sign me up then.

https://github.com/kalimatas/php-liquid/settings/collaboration

If else, it should be possible to move the project into an organisation, where more things possible.

**Comment by kalimatas** [comment]
Done. Thanks for helping!

**Comment by sanmai** [comment]
Thanks! I'll try my best.

**Comment by schmoove** [comment]
Thanks to you both for all your work on this - much appreciated!

**Pull request merged**
