### PR TITLE
Changes from other Forks

### PR DESCRIPTION
**Pull request by ryanmitchell**
Hello

As discussed I've compiled changes from other forks and added a few missing tags. 

Ryan

### CODE REVIEW

**Comment by kalimatas** [comment]
Unfortunately, I cannot accept this pull request now - there are errors in code. I found them just by trying to run the tests. Just a few for example:

1. TagIfchangedTest.

```
Fatal error: Cannot redeclare class Liquid\Tag\TagIfTest in /Users/kalimatas/p/php/php-liquid-pull-request/tests/Liquid/Tag/TagIfchangedTest.php on line 30
```

2. T_DEFAULT. default is a reserved word in PHP.

```
Parse error: syntax error, unexpected 'default' (T_DEFAULT), expecting identifier (T_STRING) in /Users/kalimatas/p/php/php-liquid-pull-request/src/Liquid/StandardFilters.php on line 85
```

3. sort_key

```
Fatal error: Call to undefined method Liquid\StandardFilters::sort_key() in /Users/kalimatas/p/php/php-liquid-pull-request/tests/Liquid/StandardFiltersTest.php on line 421
```

4. LiquidRegexp

```
Fatal error: Class 'Liquid\Tag\LiquidRegexp' not found in /Users/kalimatas/p/php/php-liquid-pull-request/src/Liquid/Tag/TagFor.php on line 79
```

And a lot of other errors. Just run tests.

Beside the errors, I would like to maintain the same coding style standards. Here is what I’ve found so far and what should be changed: 
1. camelCase should be used for variable names
2. New line at the end of files (here is [why](http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline))
3. Curly brackets placement: on a new line after a class definition, on the same line for methods and other constructions (if, foreach, etc.)
4. No ‘_’ underscore symbol in variables’ names
5. Indentation and spaces

**Comment by ryanmitchell** [comment]
Thanks - I just compiled the code from other forks and didn't really go through for syntax and style changes - do you have a reference to the syntax style you are trying to achieve so I can ensure everything matches?

I'll work those through when I next get a chance and notify you when updates have been made.

Incidentally, sort_key is not a standard liquid filter - see:
http://www.rubydoc.info/gems/liquid/Liquid/StandardFilters

It would be good to clarify if you are trying to feature match ruby's Liquid or create a different feature set as I've been working on the assumption we were aiming for feature parity with ruby's Liquid.

**Comment by kalimatas** [comment]
About `sort_key` filter. When I forked the repo, this filter was already there, and I decided not to delete it. I don't mind to make the list of filters equal to Ruby's, but for backward compatibility I suggest to retain already excess filters.

**Comment by kalimatas** [comment]
About coding style. I mostly stick with [Symfony's standards](http://symfony.com/doc/current/contributing/code/standards.html), except for the opening `{` for methods - I place it at the same line :)

**Comment by ryanmitchell** [comment]
Ok - how about keeping StandardFilters as ruby compatible, and then creating a CustomFilters bank which has non-standard ones it. ?

See my last commit:

https://github.com/ryanmitchell/php-liquid/commit/1af0532460f38d27ef0c26fe1b266d080e8b980a <https://github.com/ryanmitchell/php-liquid/commit/1af0532460f38d27ef0c26fe1b266d080e8b980a>

**Comment by ryanmitchell** [comment]
Ok - the last set of changes I’ve just should bring it pretty close then - it was mostly whitespace around braces from what I could see.

Its different from the style I’m used to, so I may have missed a few!

**Comment by ryanmitchell** [comment]
This should be all the fixes made you suggested and the Travis builds are now passing.

**Comment by kalimatas** [comment]
Hey Ryan

Thanks for fixing. But there are still errors to fix and a few remarks to be made. 

1. I ran an inspection in PHPStorm on `src` folder, here is what I got https://yadi.sk/i/hil-h5zjgsiRb and https://yadi.sk/i/Z1ZwsSbGgsiTo.

2. File for `TagIfChanged` class should be `TagIfChanged.php` with a capital `C`. Perhaps, you would have to set a `ignorecase` setting in your `.gitconfig`.

3. `escape` filter. No need to use `str_replace`, there is a function `htmlspecialchars`.

4. `TagPaginate`. Well, first of all, there is no example in class documentaion and there are no tests for this tag. But there is more interesting problem: I think it's not OK to use superglobal arrays like `$_GET` and `$_SERVER` inside the class - we should pass the parameters, like current page and current URL, via the parameters at call time. It may be a problem, if you run the code from the command line, which is  a real-wold scenario, when you want to generate the cache in advance. What do you think about these arrays?

**Comment by ryanmitchell** [comment]
Hi

Thanks for bearing with me on this.

> I ran an inspection in PHPStorm on src folder, here is what I got https://yadi.sk/i/hil-h5zjgsiRb and https://yadi.sk/i/Z1ZwsSbGgsiTo.

I've fixed up these errors

> File for TagIfChanged class should be TagIfChanged.php with a capital C. Perhaps, you would have to set a ignorecase setting in your .gitconfig.

This had been changed, but hadn't gone through - so I've applied it again

> escape filter. No need to use str_replace, there is a function htmlspecialchars.

I was trying to replicate the ruby liquid functionality rather than use a in-built PHP function - see:
https://github.com/Shopify/liquid/commit/5e8f2f8bd04d3d89e2e0fd45bec49c4e831ff8ed

> TagPaginate. Well, first of all, there is no example in class documentaion and there are no tests for this tag. But there is more interesting problem: I think it's not OK to use superglobal arrays like $_GET and $_SERVER inside the class - we should pass the parameters, like current page and current URL, via the parameters at call time. It may be a problem, if you run the code from the command line, which is a real-wold scenario, when you want to generate the cache in advance. What do you think about these arrays?

I've applied a few fixes here - pulling var's down from context rather than $_GET and $_SERVER (note the change to Context.php), and I have also added and verified test cases.

**Comment by ryanmitchell** [comment]
The last failures are due to the "Ifchanged" -> "IfChanged" fix - I understand the desire for the naming convention, however it means the tag is not found (see AbstractBlock.php line #67).

 I'm not sure how you want me to proceed with this?

**Comment by kalimatas** [comment]
Hmm, I think we can use `Ifchanged` with a small `c` for now, later I'll think of something.

A few more bugs:

1. `escape_once`. Wrong usage of `str_replace` - do not pass the fourth parameter, because it's not the limit of replacements, but rather a variable that will hold the number of replacements perfomed, but we don't need it here.

2. `TagPaginate`. Field `currentOffset` not found in class. You should declare it.

3. `TagFor`. Undefined variable `syntax_regexp` at line 84.

**Comment by ryanmitchell** [comment]
I've updated this PR now with the items you last mentioned and some additional things I noticed.

**Comment by kalimatas** [comment]
Thanks!

**Comment by ryanmitchell** [comment]
Great - glad we got there eventually!

**Pull request merged**
