### PR TITLE
Allow negative numbers & Support strings and variables as array indicies

### PR DESCRIPTION
**Pull request by Eun**
`{% assign i = -100 %}` or `{% assign i = -10.0 %}` was not possible, is possible now.

TODO:
- [ ] Test numbers in `TagAssignTest.php`

### CODE REVIEW

**Comment by sanmai** [comment]
Really nice would be to have this covered with tests.

**Comment by sanmai** [comment]
Hi, I've merged support for negative numbers, thanks. Now I can't get what your other commits are about. Can you help? How are these changes supposed to work?

I can help you with tests, but for this I need to understand what to test.

**Comment by Eun** [comment]
The other commits are for the "Support strings and variables as array indicies" feature

**Comment by sanmai** [comment]
Cool, how one supposed to use variables as array indices?

**Comment by Eun** [comment]
Its a bit longer since I added this but I think it was the following snippet that did not work:

    {% assign list = '' | split: ',' %}
    {% assign list = list | push: 'a' %}
    {% assign list = list | push: 'b' %}
    {% assign list = list | push: 'c' %}
    {% assign index = 0 %}
    {{ list[index] }}

I am not sure tho. Too bad I didn't add an example...

**Comment by schmoove** [comment]
I tried pulling this to try and get it working but couldn't.

I'd already offered a solution in the original repo, which works for me:

https://github.com/harrydeluxe/php-liquid/issues/31

But wasn't sure if it was safe to use the (.*) regex.

Any suggestions appreciated - it'd be great to get this feature added.

**Comment by HappyLDE** [comment]
Was this added to the library? I still can't access arrays like {% for menu_item in menus['main'] %}

**Comment by sanmai** [comment]
This was #50. I'm pretty sure it was merged. Can you do `composer update`?

**Comment by HappyLDE** [comment]
It seems it has the latest update:
> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update

So in PHP i create this array:
`$menus = [];
    $menus['main'] = [
                      ['title'=>'one'],
                      ['title'=>'two']
                    ];`

.liquid i have this code:
`{% for menu_item in menus.main %}
    {{ menu_item.title }}
{% endfor %}`

Outputs: one two

When i try with variable index:
`{% assign menu_top = 'main' %}
{% for menu_item in menus[menu_top] %}
    {{ menu_item.title }}
{% endfor %}`

Outputs nothing
Thanks for help

**Comment by sanmai** [comment]
Will that work?

```
{% assign menu_top = 'main' %}
{% assign menu_top_items = menus[menu_top]%}
{% for menu_item in menu_top_items %} {{ menu_item.title }} {% endfor %}
```

**Comment by HappyLDE** [comment]
It does work! Thanks :)

**Pull request closed without merging**
